### ISSUE TITLE
feature request: some kind of resize support

### ISSUE THREAD

**Issue by buffos** [yo35/rpb-chessboard#26]
The only basic drawback i see in this plugin (everything else is just added features that one can ask) is difficult to use in a responsive web design. 

I tried through media queries but there is **one thing missing**
1) you set pieces through fixed styles "background position... etc" which **do not have a name** and cannot be overriden by media queries
For example you can add a
```css
@media all and (max-width: 500px){
.uichess-chessboard-piece,.uichess-chessboard-turnFlag { width: 30px !important; height: 30px !important; background-image: url(sprite/all-30.png);  }
.uichess-chessboard-square, .uichess-chessboard-rowCoordinate, .uichess-chessboard-cell ,.uichess-chessboard-turnFlag {width: 30px !important; height: 30px !important;}
}
```
but you cannot adjust the background position since you do not know which piece it is
if you had an **extra class** in the piece , for example black_knight , depending on the piece, you could adjust the background position , to find the piece, by adding few more statements to the above query

```css
@media all and (max-width: 500px){
.uichess-chessboard-piece,.uichess-chessboard-turnFlag { width: 30px !important; height: 30px !important; background-image: url(sprite/all-30.png);  }
.uichess-chessboard-square, .uichess-chessboard-rowCoordinate, .uichess-chessboard-cell ,.uichess-chessboard-turnFlag {width: 30px !important; height: 30px !important;}
.black_knight { background-position: NNpx -nnpx;}
.black_king {.......etc.....}
}
```
That way, one could create a responsive version of the board

So in short, the feature request is "when you output a piece on the board, **just add a class with a name to show what piece it is** (or if its the turnflag). The rest are taken care from the media query above (adjusted as one needs)
